// flow-typed signature: 137fe68c2b2e1445c8a4f8d8752934cb
// flow-typed version: <<STUB>>/react-native-image-picker_v^3.3.2/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-picker' {
  declare module.exports: any;
}
