// flow-typed signature: 027827add0c6bfa463c27ffb144614a7
// flow-typed version: <<STUB>>/react-native-reanimated_v^2.1.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-reanimated'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-reanimated' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-reanimated/lib/__mocks__/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/__mocks__/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/Animated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/ConfigHelper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/animations/Animation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/animations/backwardCompatibleAnimWrapper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/animations/decay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/animations/spring' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/animations/SpringUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/animations/timing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/base' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/__mocks__/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedAlways' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedBezier' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedBlock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCall' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCallFunc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedClockTest' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedConcat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCond' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedDebug' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedEvent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedFunction' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedNode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedOperator' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedParam' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedSet' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedStartClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedStopClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedTransform' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/createEventObjectProxyPolyfill' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/core/InternalAnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/__mocks__/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/acc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/color' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/diff' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/diffClamp' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/interpolate' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/interpolateColors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/onChange' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/derived/useCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/Easing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/operators' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/SpringConfig' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/Transitioning' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/useValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated1/val' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/__mocks__/MutableValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/__mocks__/NativeReanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/__mocks__/NativeReanimated.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/animations' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/Bezier' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/Colors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/core' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/Easing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/Hooks' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/interpolation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/jestUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/js-reanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/index.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/Mapper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/MapperRegistry' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/MutableValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/mock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/NativeMethods' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/NativeReanimated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/NativeReanimated.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/PropAdapters' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/react-native-reanimated-tests' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/UpdateProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/reanimated2/WorkletEventHandler' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/ReanimatedModule' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/ReanimatedModule.macos' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/ReanimatedModule.windows' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/ReanimatedModuleCompat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/lib/setAndForwardRef' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/mock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/plugin' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/__mocks__/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/__mocks__/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/Animated' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ConfigHelper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/createAnimatedComponent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/animations/Animation' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/animations/backwardCompatibleAnimWrapper' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/animations/decay' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/animations/spring' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/animations/SpringUtils' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/animations/timing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/base' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/__mocks__/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedAlways' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedBezier' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedBlock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCall' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCallFunc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedClockTest' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedConcat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCond' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedDebug' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedEvent' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedFunction' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedNode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedOperator' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedParam' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedProps' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedSet' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedStartClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedStopClock' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedStyle' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedTransform' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/AnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/createEventObjectProxyPolyfill' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/core/InternalAnimatedValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/__mocks__/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/acc' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/color' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/diff' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/diffClamp' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/evaluateOnce' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/interpolate' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/interpolateColors' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/onChange' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/derived/useCode' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/Easing' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/operators' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/SpringConfig' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/Transitioning' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/useValue' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/reanimated1/val' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedEventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule.macos' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule.native' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModule.windows' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/ReanimatedModuleCompat' {
  declare module.exports: any;
}

declare module 'react-native-reanimated/src/setAndForwardRef' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-reanimated/lib/__mocks__/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/__mocks__/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/lib/__mocks__/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/__mocks__/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/lib/Animated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/Animated'>;
}
declare module 'react-native-reanimated/lib/ConfigHelper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/ConfigHelper'>;
}
declare module 'react-native-reanimated/lib/createAnimatedComponent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/lib/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib'>;
}
declare module 'react-native-reanimated/lib/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib'>;
}
declare module 'react-native-reanimated/lib/reanimated1/animations/Animation.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/animations/Animation'>;
}
declare module 'react-native-reanimated/lib/reanimated1/animations/backwardCompatibleAnimWrapper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/animations/backwardCompatibleAnimWrapper'>;
}
declare module 'react-native-reanimated/lib/reanimated1/animations/decay.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/animations/decay'>;
}
declare module 'react-native-reanimated/lib/reanimated1/animations/spring.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/animations/spring'>;
}
declare module 'react-native-reanimated/lib/reanimated1/animations/SpringUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/animations/SpringUtils'>;
}
declare module 'react-native-reanimated/lib/reanimated1/animations/timing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/animations/timing'>;
}
declare module 'react-native-reanimated/lib/reanimated1/base.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/base'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/__mocks__/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/__mocks__/AnimatedProps'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedAlways.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedAlways'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedBezier.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedBezier'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedBlock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedBlock'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCall.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedCall'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCallFunc.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedCallFunc'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedClock'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedClockTest.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedClockTest'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedCode'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedConcat.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedConcat'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedCond.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedCond'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedDebug.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedDebug'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedEvent.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedEvent'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedFunction.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedFunction'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedNode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedNode'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedOperator.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedOperator'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedParam.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedParam'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedProps'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedSet.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedSet'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedStartClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedStartClock'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedStopClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedStopClock'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedStyle.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedStyle'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedTransform.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedTransform'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/AnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/AnimatedValue'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/createEventObjectProxyPolyfill.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/createEventObjectProxyPolyfill'>;
}
declare module 'react-native-reanimated/lib/reanimated1/core/InternalAnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/core/InternalAnimatedValue'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/__mocks__/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/__mocks__/evaluateOnce'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/acc.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/acc'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/color.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/color'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/diff.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/diff'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/diffClamp.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/diffClamp'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/evaluateOnce'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/interpolate.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/interpolate'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/interpolateColors.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/interpolateColors'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/onChange.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/onChange'>;
}
declare module 'react-native-reanimated/lib/reanimated1/derived/useCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/derived/useCode'>;
}
declare module 'react-native-reanimated/lib/reanimated1/Easing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/Easing'>;
}
declare module 'react-native-reanimated/lib/reanimated1/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1'>;
}
declare module 'react-native-reanimated/lib/reanimated1/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1'>;
}
declare module 'react-native-reanimated/lib/reanimated1/operators.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/operators'>;
}
declare module 'react-native-reanimated/lib/reanimated1/SpringConfig.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/SpringConfig'>;
}
declare module 'react-native-reanimated/lib/reanimated1/Transitioning.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/Transitioning'>;
}
declare module 'react-native-reanimated/lib/reanimated1/useValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/useValue'>;
}
declare module 'react-native-reanimated/lib/reanimated1/val.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated1/val'>;
}
declare module 'react-native-reanimated/lib/reanimated2/__mocks__/MutableValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/__mocks__/MutableValue'>;
}
declare module 'react-native-reanimated/lib/reanimated2/__mocks__/NativeReanimated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/__mocks__/NativeReanimated'>;
}
declare module 'react-native-reanimated/lib/reanimated2/__mocks__/NativeReanimated.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/__mocks__/NativeReanimated.native'>;
}
declare module 'react-native-reanimated/lib/reanimated2/animations.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/animations'>;
}
declare module 'react-native-reanimated/lib/reanimated2/Bezier.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/Bezier'>;
}
declare module 'react-native-reanimated/lib/reanimated2/Colors.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/Colors'>;
}
declare module 'react-native-reanimated/lib/reanimated2/core.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/core'>;
}
declare module 'react-native-reanimated/lib/reanimated2/Easing.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/Easing'>;
}
declare module 'react-native-reanimated/lib/reanimated2/Hooks.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/Hooks'>;
}
declare module 'react-native-reanimated/lib/reanimated2/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2'>;
}
declare module 'react-native-reanimated/lib/reanimated2/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2'>;
}
declare module 'react-native-reanimated/lib/reanimated2/interpolation.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/interpolation'>;
}
declare module 'react-native-reanimated/lib/reanimated2/jestUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/jestUtils'>;
}
declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/index' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/js-reanimated'>;
}
declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/js-reanimated'>;
}
declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/index.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/js-reanimated/index.web'>;
}
declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated'>;
}
declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/Mapper.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/js-reanimated/Mapper'>;
}
declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/MapperRegistry.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/js-reanimated/MapperRegistry'>;
}
declare module 'react-native-reanimated/lib/reanimated2/js-reanimated/MutableValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/js-reanimated/MutableValue'>;
}
declare module 'react-native-reanimated/lib/reanimated2/mock.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/mock'>;
}
declare module 'react-native-reanimated/lib/reanimated2/NativeMethods.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/NativeMethods'>;
}
declare module 'react-native-reanimated/lib/reanimated2/NativeReanimated.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/NativeReanimated'>;
}
declare module 'react-native-reanimated/lib/reanimated2/NativeReanimated.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/NativeReanimated.native'>;
}
declare module 'react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer'>;
}
declare module 'react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/platform-specific/RNRenderer.web'>;
}
declare module 'react-native-reanimated/lib/reanimated2/PropAdapters.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/PropAdapters'>;
}
declare module 'react-native-reanimated/lib/reanimated2/react-native-reanimated-tests.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/react-native-reanimated-tests'>;
}
declare module 'react-native-reanimated/lib/reanimated2/UpdateProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/UpdateProps'>;
}
declare module 'react-native-reanimated/lib/reanimated2/WorkletEventHandler.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/reanimated2/WorkletEventHandler'>;
}
declare module 'react-native-reanimated/lib/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/lib/ReanimatedModule.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/ReanimatedModule'>;
}
declare module 'react-native-reanimated/lib/ReanimatedModule.macos.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/ReanimatedModule.macos'>;
}
declare module 'react-native-reanimated/lib/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/lib/ReanimatedModule.windows.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/ReanimatedModule.windows'>;
}
declare module 'react-native-reanimated/lib/ReanimatedModuleCompat.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/ReanimatedModuleCompat'>;
}
declare module 'react-native-reanimated/lib/setAndForwardRef.js' {
  declare module.exports: $Exports<'react-native-reanimated/lib/setAndForwardRef'>;
}
declare module 'react-native-reanimated/mock.js' {
  declare module.exports: $Exports<'react-native-reanimated/mock'>;
}
declare module 'react-native-reanimated/plugin.js' {
  declare module.exports: $Exports<'react-native-reanimated/plugin'>;
}
declare module 'react-native-reanimated/src/__mocks__/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/__mocks__/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/src/__mocks__/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/__mocks__/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/src/Animated.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/Animated'>;
}
declare module 'react-native-reanimated/src/ConfigHelper.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ConfigHelper'>;
}
declare module 'react-native-reanimated/src/createAnimatedComponent.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/createAnimatedComponent'>;
}
declare module 'react-native-reanimated/src/reanimated1/animations/Animation.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/animations/Animation'>;
}
declare module 'react-native-reanimated/src/reanimated1/animations/backwardCompatibleAnimWrapper.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/animations/backwardCompatibleAnimWrapper'>;
}
declare module 'react-native-reanimated/src/reanimated1/animations/decay.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/animations/decay'>;
}
declare module 'react-native-reanimated/src/reanimated1/animations/spring.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/animations/spring'>;
}
declare module 'react-native-reanimated/src/reanimated1/animations/SpringUtils.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/animations/SpringUtils'>;
}
declare module 'react-native-reanimated/src/reanimated1/animations/timing.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/animations/timing'>;
}
declare module 'react-native-reanimated/src/reanimated1/base.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/base'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/__mocks__/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/__mocks__/AnimatedProps'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedAlways.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedAlways'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedBezier.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedBezier'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedBlock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedBlock'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCall.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedCall'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCallFunc.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedCallFunc'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedClock'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedClockTest.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedClockTest'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedCode'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedConcat.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedConcat'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedCond.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedCond'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedDebug.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedDebug'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedEvent.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedEvent'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedFunction.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedFunction'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedNode.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedNode'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedOperator.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedOperator'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedParam.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedParam'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedProps.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedProps'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedSet.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedSet'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedStartClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedStartClock'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedStopClock.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedStopClock'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedStyle.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedStyle'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedTransform.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedTransform'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/AnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/AnimatedValue'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/createEventObjectProxyPolyfill.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/createEventObjectProxyPolyfill'>;
}
declare module 'react-native-reanimated/src/reanimated1/core/InternalAnimatedValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/core/InternalAnimatedValue'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/__mocks__/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/__mocks__/evaluateOnce'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/acc.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/acc'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/color.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/color'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/diff.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/diff'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/diffClamp.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/diffClamp'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/evaluateOnce.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/evaluateOnce'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/index' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/interpolate.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/interpolate'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/interpolateColors.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/interpolateColors'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/onChange.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/onChange'>;
}
declare module 'react-native-reanimated/src/reanimated1/derived/useCode.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/derived/useCode'>;
}
declare module 'react-native-reanimated/src/reanimated1/Easing.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/Easing'>;
}
declare module 'react-native-reanimated/src/reanimated1/index' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1'>;
}
declare module 'react-native-reanimated/src/reanimated1/index.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1'>;
}
declare module 'react-native-reanimated/src/reanimated1/operators.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/operators'>;
}
declare module 'react-native-reanimated/src/reanimated1/SpringConfig.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/SpringConfig'>;
}
declare module 'react-native-reanimated/src/reanimated1/Transitioning.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/Transitioning'>;
}
declare module 'react-native-reanimated/src/reanimated1/useValue.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/useValue'>;
}
declare module 'react-native-reanimated/src/reanimated1/val.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/reanimated1/val'>;
}
declare module 'react-native-reanimated/src/ReanimatedEventEmitter.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedEventEmitter'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.macos.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule.macos'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.native.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule.native'>;
}
declare module 'react-native-reanimated/src/ReanimatedModule.windows.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModule.windows'>;
}
declare module 'react-native-reanimated/src/ReanimatedModuleCompat.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/ReanimatedModuleCompat'>;
}
declare module 'react-native-reanimated/src/setAndForwardRef.js' {
  declare module.exports: $Exports<'react-native-reanimated/src/setAndForwardRef'>;
}
