// flow-typed signature: 13350397342f53fa448b0889da88157c
// flow-typed version: <<STUB>>/redux-api-call_v^1.2.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-api-call'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-api-call' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-api-call/dist/redux-api-call.cjs' {
  declare module.exports: any;
}

declare module 'redux-api-call/dist/redux-api-call.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-api-call/dist/redux-api-call.cjs.js' {
  declare module.exports: $Exports<'redux-api-call/dist/redux-api-call.cjs'>;
}
declare module 'redux-api-call/dist/redux-api-call.es.js' {
  declare module.exports: $Exports<'redux-api-call/dist/redux-api-call.es'>;
}
